### ISSUE TITLE
ENH:  Support setting/updating meta data from data catalog (e.g., units)

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#327] opened 2023-04-20 07:29 UTC
### Feature Type

- Adding new functionality to HydroMT

### Enhancement Description

Add functionality that updates/sets the the meta data of datasets in the datacatalog. An example would be the unit of the data.

### Feature Description

Add `attrs` object in **data catalog yml file**
```
era5_hourly:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  meta:
    category: meteo
  path: meteo/era5/{variable}/era5_{variable}_{year}_hourly.nc
  rename:
    t2m: temp
    tp: precip
  unit_add:
    temp: -273.15
  unit_mult:
    precip: 1000
  attrs:  
    temp: # var name
      units: degree C
      long_name: temperature
    precip:
      units: mm
```

In the **code**
- in `DataAdapter.__init__` add a `attrs` attribute
- in `RasterDatasetAdapter`, `GeoDatasetAdapter` (check if also possible for `DataFrameAdapter` and `GeoDataFrameAdapter`) after setting the global `meta` data, set the `attrs` for each variable with `ds[var].attrs.update(**self.attrs[var])`
- in `RasterDatasetAdapter` remove `units` argument which is duplicate with this enhancement.

**Comment by DirkEilander** [comment] 2023-04-20 08:57
@hboisgon Can you let us know what you think of using `attrs`. We also discussed combining it with `meta`. Not sure what is more clear for users.  This implementation would also make the `units` argument redundant.

**Comment by hboisgon** [comment] 2023-04-21 03:48
I think `attrs` is a good idea and indeed then we can remove `units` which is only used by hydromt-delwaq anyhow. I think using `attrs` rather than `meta` would be clearer as potentially if you do unit_conversion then you will change the dataset set unit attrs compared to the original data and I think anything in `meta` does not have any impact within hydromt code but is more here for info/reproducibility so better keep it that way that the code does not do anything with the keys in `meta`.

**Comment by DirkEilander** [comment] 2023-04-21 07:20
Thanks for the feedback @hboisgon, so we are on the same line! 

After discussion with @Tjalling-dejong yesterday we realized that a new `attrs` property in the data catalog file would results in errors if loaded with the current hydromt release. This is because of the way we deal with `kwargs` that are passed to the driver, see below. It would good to remove L908-L910 from data_catalog.py and make `kwargs` an explicit argument of `DataAdapter`. This won't fix the error though, but it does make it more future proof.
https://github.com/Deltares/hydromt/blob/ca0b810b12f89e8ee7b4df12ea4bfc5aabf548c3/hydromt/data_catalog.py#L908

In addition to avoid these kind of errors in the future, I think we should add a catalog version number in the catalog meta so that we can deal with changes in the format when parsing the yml files.

**Comment by Tjalling-dejong** [comment] 2023-05-04 13:07
@DirkEilander see PR #334 related to this issue. I fixed the issue by popping the attrs from "source" dict in _parse_data_dict() and explicitly giving it to the data adapter object. This prevents the attrs from ending up in the kwargs.

**Comment by DirkEilander** [comment] 2023-05-05 13:31
Thanks for the PR @Tjalling-dejong. In general I think it looks good, but I'd also like remove L908-L910 from data_catalog.py mentioned in my earlier comment and pass `kwargs` explicitly to all DataAdapter classes (similar to how you did the `attrs`) to make it more future proof. Can you add this, then I'll give it a thorough review.

**Comment by Tjalling-dejong** [comment] 2023-05-11 16:00
I implemented explicit kwargs as driver_kwargs in the _parse_data_dict function and data adapter classes. Unfortunately I have not managed to fix the failing tests yet. Still WIP.

**Comment by Tjalling-dejong** [comment] 2023-06-01 15:33
I managed to fix most of the failing tests. However, I've run in to some issues with the `get_dataframe` method in data_catalog.py. In this method `DataFrameAdapter` is called and kwargs are passed to this class. The only way I found I could make this work with the driver_kwargs is to explicitly pop and then pass all the parameters in `DataFrameAdapter` and pass the residual kwargs as driver_kwargs. It does not feel like this is best practice since it still allows for passing wrong kwargs to for example  `pd.read_csv()`. @hboisgon do you maybe have an idea how I could tackle this?

**Comment by hboisgon** [comment] 2023-06-02 00:55
Hi @Tjalling-dejong , I would really keep ``kwargs`` as else you are creating backward compatibility issue the same way you would if you would have added a ``attrs`` one.

Just add a very quick look but at the beginning of the get_data, you could pop attrs out of kwargs if they are present:
`if 'attrs' in self.kwargs: attrs = kwargs.pop(attrs)`
With this you delete attrs from kwargs and get attrs for your update of attributes later.

Would that solve your issue?

**Comment by hboisgon** [comment] 2023-06-02 01:18
I looked more closely and I think what Dirk meant is that when we initialise an adapter we make all arguments explicit:

https://github.com/Deltares/hydromt/blob/ae7650d8462e2d559741ebaf12e59a01c28d8649/hydromt/data_catalog.py#L937-L945

Would now be:
data[name_n] = adapter(
      path=path_n,
      name=name_n,
      catalog_name=catalog_name,
      meta=meta,
        driver=driver,
        filesystem=filesystem,
        crs=crs,
        nodata=nodata,
        rename=rename,
        unit_mult=unit_mult,
        unit_add=unit_add,
        zoom_levels=zoom_levels,
        attrs=attrs,
      kwargs=kwargs,  # key word arguments specific to certain adaptors
  )

**Comment by hboisgon** [comment] 2023-06-02 01:26
I still wonder if I like to put ``attrs`` in ``kwargs`` and not on its own though, this is quite confusing as kwargs should be more or less really for the read driver which is what we put in the docs.
Is the error message very unclear? I would prefer to add attrs on its own for now and maybe delay the update of the predefined catalogs (or for a while latest data catalog version point to older catalogs)? Also in this PR start or in the meantime start looking in to adding a hydromt version in the catalog meta and write some code that compares it to the current version and warns the user / throws error (see #331 )

**Comment by Tjalling-dejong** [comment] 2023-06-08 09:53
Thanks @hboisgon for the feedback. 
`attrs` has its own key in a data catalog source. What I am struggling with at the moment is that when manually adding datasets to a datacatalog the arguments passed to for instance `datacatalog.get_dataframe()`  are directly passed as kwargs to `pd.read_csv()'. Some of these kwargs should not be passed to pd.read_csv(). 

Here is an example of code that throws an error because of the above mentioned issue:
`dfts3 = data_catalog.get_dataframe(
            file_path , index_col=0, parse_dates=True, unit_mult=unit_mult, unit_add=unit_add
        )
`

`unit_mult` and `unit_add` are not arguments you can pass to pd.read_csv(). I would need to pop those arguments explicitly from the kwargs passed to data_catalog.get_dataframe() and then pass the remaining kwargs as kwargs for the read driver.

**Comment by Tjalling-dejong** [comment] 2023-06-08 10:47
> I still wonder if I like to put `attrs` in `kwargs` and not on its own though, this is quite confusing as kwargs should be more or less really for the read driver which is what we put in the docs. Is the error message very unclear? I would prefer to add attrs on its own for now and maybe delay the update of the predefined catalogs (or for a while latest data catalog version point to older catalogs)? Also in this PR start or in the meantime start looking in to adding a hydromt version in the catalog meta and write some code that compares it to the current version and warns the user / throws error (see #331 )

I added a check for hydromt version  in the datacatalog. If the versions do not match a warning will be displayed.

**Comment by hboisgon** [comment] 2023-06-09 01:53
> Thanks @hboisgon for the feedback. `attrs` has its own key in a data catalog source. What I am struggling with at the moment is that when manually adding datasets to a datacatalog the arguments passed to for instance `datacatalog.get_dataframe()` are directly passed as kwargs to `pd.read_csv()'. Some of these kwargs should not be passed to pd.read_csv().
> 
> Here is an example of code that throws an error because of the above mentioned issue: `dfts3 = data_catalog.get_dataframe( file_path , index_col=0, parse_dates=True, unit_mult=unit_mult, unit_add=unit_add ) `
> 
> `unit_mult` and `unit_add` are not arguments you can pass to pd.read_csv(). I would need to pop those arguments explicitly from the kwargs passed to data_catalog.get_dataframe() and then pass the remaining kwargs as kwargs for the read driver.

Hi @Tjalling-dejong. I'm not sure I follow how ``unit_mult`` and ``unit_add`` ended in pd.read_csv function? If you look at my example above for data_catalog.py they should be distinct from ``kwargs`` no? If still not working I can try and have a look at it

**Comment by Tjalling-dejong** [comment] 2023-06-09 14:38
That would require that all DataAdapter subclasses should have the same arguments, even if some of these arguments are not used in certain subclasses. I'm not sure if that is good practice. Please have a look at, because I'm getting a bit lost with this issue.

**Closed** 2023-07-10 07:33 UTC
Labels: Enhancement, DataCatalog & DataAdapters
