### ISSUE TITLE
ERROR - No data within spatial domain.

### ISSUE THREAD

**Issue by aweerts** [Deltares/hydromt#713] opened 2024-01-10 08:57 UTC
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

[wflow_build_1km_vito_hydromt3.ini.txt](https://github.com/Deltares/hydromt/files/13885308/wflow_build_1km_vito_hydromt3.ini.txt)

2024-01-10 06:31:48,534 - build - model_api - INFO - setup_basemaps.region: {'subbasin': [139.429166666376, 35.7791666666275], 'strord': 4, 'bounds': [139.315, 35.7133333333333, 139.479166666667, 35.8358333333333]}

### Current behaviour

2024-01-10 06:32:11,887 - build - model_api - INFO - setup_lakes.add_maxstorage: False
2024-01-10 06:32:11,887 - build - wflow - INFO - Preparing lake maps.
2024-01-10 06:32:11,889 - build - geodataframe - INFO - Reading hydro_lakes vector data from /data/hydromt/hydrography/lakes/lake-db.fgb
2024-01-10 06:32:15,502 - build - geodataframe - DEBUG - Clip contains [139.365, 35.763, 139.429, 35.786] (EPSG:4326)
2024-01-10 06:32:15,503 - build - main - ERROR - No data within spatial domain.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hydromt/cli/main.py", line 226, in build
    mod.build(region, opt=opt)
  File "/opt/conda/lib/python3.10/site-packages/hydromt/models/model_api.py", line 236, in build
    self._run_log_method(method, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/hydromt/models/model_api.py", line 178, in _run_log_method
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/hydromt_wflow/wflow.py", line 1426, in setup_lakes
    gdf_org, ds_lakes = self._setup_waterbodies(lakes_fn, "lake", min_area)
  File "/opt/conda/lib/python3.10/site-packages/hydromt_wflow/wflow.py", line 1684, in _setup_waterbodies
    gdf_org = self.data_catalog.get_geodataframe(
  File "/opt/conda/lib/python3.10/site-packages/hydromt/data_catalog.py", line 1480, in get_geodataframe
    gdf = source.get_data(
  File "/opt/conda/lib/python3.10/site-packages/hydromt/data_adapter/geodataframe.py", line 257, in get_data
    gdf = GeoDataFrameAdapter._slice_data(
  File "/opt/conda/lib/python3.10/site-packages/hydromt/data_adapter/geodataframe.py", line 375, in _slice_data
    _exec_nodata_strat(
  File "/opt/conda/lib/python3.10/site-packages/hydromt/nodata.py", line 18, in _exec_nodata_strat
    raise NoDataException(msg)
hydromt.exceptions.NoDataException: No data within spatial domain.

### Desired behaviour

Before model building continued without lakes if there is no lake data

**Comment by DirkEilander** [comment] 2024-01-10 11:47
This should be fixed in HydroMT-Wflow. We have now introduced explicit no data handling in HydroMT core, while before the behaviour was different per data time. In HydroMT-Wflow the the [get_geodataframe](https://deltares.github.io/hydromt/latest/_generated/hydromt.data_catalog.DataCatalog.get_geodataframe.html#hydromt.data_catalog.DataCatalog.get_geodataframe) method in _setup_waterbodies requires a new argument `handle_nodata=NoDataStrategy.Ignore` at this [line](https://github.com/Deltares/hydromt_wflow/blob/e3f313c37d4b6141a74b1416f7ac1d503e01a4a8/hydromt_wflow/wflow.py#L1690C37-L1690C53) 

@dalmijn @JoostBuitink Can you make an issue for this in HydroMT-Wflow?

**Comment by JoostBuitink** [comment] 2024-01-10 11:56
I believe this issue (https://github.com/Deltares/hydromt_wflow/issues/208) is already dedicated to this error. I noticed that some work has already been started in this PR: https://github.com/Deltares/hydromt_wflow/pull/216, but I don't know about the status (mabe @Jaapel can update us?)

**Comment by Jaapel** [comment] 2024-01-10 15:54
I updated HydroMT-Wflow to get the cloud pilot working. I implemented a `NoDataStrategy`, where you can define how to handle the situations where no data is found. I retained the default behaviour and all tests still ran, so if you want to make use of it you can change this behaviour in the workflow, or use a try except like I in this stale PR. If you want to discuss it feel free to send me a message.

**Comment by aweerts** [comment] 2024-01-11 09:00
@Jaapel where and how can I define a NoDataStrategy? No model building fails when i uncomment lakes,reservoirs,rgi, and gauges.

**Comment by JoostBuitink** [comment] 2024-01-11 16:18
Closing this issue, as it is a duplicate of https://github.com/Deltares/hydromt_wflow/issues/208.

**Closed by JoostBuitink** 2024-01-11 16:18 UTC
Labels: Plugin

**Comment by Jaapel** [comment] 2024-01-16 10:16
@aweerts I solved this in the PR @JoostBuitink mentioned by catching the error in the hydromt_wflow code, and defining what to do with it. But the proper way to implement this is to choose per dataset what we should do when you get back an empty dataset. For version 1 of hydromt we are looking to implement this behavior proper. But the implementation for specific model components should come from the plugin (for example, for wflow, it is perhaps fine to not have any reservoirs in you area of interest).
