### ISSUE TITLE
Building a model results not supported file format error

### ISSUE THREAD

**Issue by RubenImhoff** [Deltares/hydromt#742] opened 2024-01-19 10:50 UTC
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

[wflow_build_1km_europe_pfafstetter_level_6.ini.txt](https://github.com/Deltares/hydromt/files/13988004/wflow_build_1km_europe_pfafstetter_level_6.ini.txt)
[deltares_data.yml.txt](https://github.com/Deltares/hydromt/files/13988013/deltares_data.yml.txt)
[individual_basins_pfafstetter_level6_filtered.zip](https://github.com/Deltares/hydromt/files/13988020/individual_basins_pfafstetter_level6_filtered.zip)

See the attached shapefile, deltares_data.yml file used on the HPC cluster and used ini-file to reproduce the case.

### Current behaviour

[slurm-739735.txt](https://github.com/Deltares/hydromt/files/13987975/slurm-739735.txt)

See attached file for the error (`ERROR - '/vsimem/cb24f46d5b8f405a8e51edc230ba61f6' not recognized as a supported file format.`). 

### Desired behaviour

merit_hydro_ihu should be found without problems during the step `build - rasterdataset - INFO - Reading merit_hydro_ihu raster data from /mnt/proj3/dd-23-93/hydromt/topography/merit_hydro_ihu/30sec/*.tif`

**Comment by RubenImhoff** [comment] 2024-01-19 10:52
By the way, the model is build through the command line on HPC cluster Karolina, through a StreamFlow workflow manager. After activating the environment, the following is called:

```
baseCommand: hydromt
arguments: ["build", "wflow", "$(inputs.output_dirname)/$(inputs.catchment_name)", 
"-r", "{'basin': './models_europe/individual_basins/pfafstetter_level6/$(inputs.catchment_name).shp'}",
"-i", "./models_europe/hydromt_ini_files/$(inputs.ini_file)",
"-d", "/mnt/proj3/dd-23-93/hydromt/deltares_data.yml",
"-vv"]
```

**Comment by RubenImhoff** [comment] 2024-01-19 13:04
After trying it locally, I also run into an error (a different one), but also here right after reading the merit_hydro_ihu raster data (30 sec .tif files). Locally, hydromt gives an error because it cannot find `.hydromt_data/artifact_data/0.0.8/data_catalog.yml'. That is correct, because this file is not present there. However, I am giving it a data_catalog with the -d argument, so what goes wrong?

**Comment by Jaapel** [comment] 2024-01-22 08:53
I see what is happening. We open the file in memory, and then we read it through geopandas `read_file`. This in-memory file is automatically represented in gdal as a virtual memory file in `/vsimem/{uid}` without extention and then fails. This will be fixed by more dedicated drivers. For now we can avoid reading files in memory in the `DataAdapters`, but this will result in losing information when using `filesystem` options (for example).

**Comment by Jaapel** [comment] 2024-01-22 10:43
Can you install from https://github.com/Deltares/hydromt/pull/747 and check out your results? @RubenImhoff

**Comment by RubenImhoff** [comment] 2024-01-22 10:54
Will do so this afternoon, thanks @Jaapel!

**Comment by RubenImhoff** [comment] 2024-01-22 14:16
It still gives the same error, although I was expecting that your fix would have solved it..

**Comment by Jaapel** [comment] 2024-01-22 14:51
Can you send me the log again?

**Comment by RubenImhoff** [comment] 2024-01-22 15:22
[slurm-750085.out.txt](https://github.com/Deltares/hydromt/files/14012071/slurm-750085.out.txt)

This is the most recent one.

**Comment by DirkEilander** [comment] 2024-01-23 07:54
I cannot reproduce this locally, can you @Jaapel ?
I've tried the following with the file supplied at the start of this issue:

```py
import hydromt
region = {"basin":  "./pfafstetter_Europe_12000uparea_164750.shp"}
hydromt.workflows.parse_region(region)
```

@RubenImhoff does your workflow run if you convert the shapefile to another file format e.g., GeoPackage or FlatGeoBuf? 
See [ogr2ogr doc example](https://gdal.org/programs/ogr2ogr.html#examples)

**Comment by RubenImhoff** [comment] 2024-01-25 09:20
Hi Dirk, I can give that a try. Will let you know.

**Comment by RubenImhoff** [comment] 2024-01-25 13:13
@DirkEilander and @Jaapel, I tried it with a GeoPackage and that solves this issue. :)

**Closed** 2024-02-06 07:34 UTC
Labels: Bug, Needs refinement
