### ISSUE TITLE
Better dependencies versions with each hydromt release

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#428] opened 2023-06-28 12:50 UTC
### Kind of request

None

### Enhancement Description

The python world evolves quite fast so with each hydromt release we make, it could happen that we could not run released versions of HydroMT pretty fast if we do not install the right versions of the other dependencies (gdal, fiona, xarray etc.).

I'm not sure if there is a standard way in python/conda world on how to install older versions of packages or if within hydromt pyproject toml we are keeping track properly of the dependencies and versions that should be installed? Something we could maybe do is produce with each release a environment file that has a full list of dependencies with correct versions to install to work with the version of hydromt we are releasing ? 

### Use case

I want to install or work with an older version of hydromt.

This has potentially implications on if we want to support older releases, also if plugins would not move fast enough compared to core.

**Comment by DirkEilander** [comment] 2023-06-30 09:38
Could publishing docker containers solve this? @savente93 Any thoughts?

**Comment by savente93** [comment] 2023-07-03 06:43
I will take some more time to thing through a proper solution here. Some comments in the mean time: 

- publishing a docker image _could_ help with this but it's a very blunt approach, namely it would always give you a correct and working installation (providing we test it properly, which we do), but you can't then use it outside of the container, or upgrade it in any way. it's a very "all or nothing" solution 
- The usual solution for this type of problem is called a "lockfile". Whereas the `environment.yml` describes what to include in an environment/how to build it (e.g. the blueprint) a lockfile describes just a environment but with exact dependency information in a machine readable format. it is very common to include a lockfile in the repository so users have a stable foundation (this does not prevent them from upgrading themselves if they wish). Irritatingly conda is one of the few package management systems that doesn't have support for a lockfile out of the box, though I'm sure someone has thought of this. 

I will do some further digging on how to solve this. How urgent is this issue?

**Comment by DirkEilander** [comment] 2023-07-03 09:46
I've used [conda-lock](https://conda.github.io/conda-lock/) for creating lock files in the past. Including a lock file in the repository means we also need to maintain this file, hence this should be automated to work.

As we will start publishing docker images with each release I think this has low priority.

**Comment by savente93** [comment] 2024-01-02 13:33
providing HydroMT through Pixi would also solve this since pixi has lockfiles.

**Comment by DirkEilander** [comment] 2024-01-04 11:17
@savente93 What do you mean with "providing hydromt through pixi"?

Currently, if I'm not mistaken, to use the pixi.lock file we would need to define our dependencies in the pixi.toml file itself next to the pyproject.toml file. Pixi is planning to support pyproject.toml. If this can be done in a way that is compatible with pip that would make using pixi a whole lot more interesting.

The conda-lock tool allows for creating (and installing from) the same type of lock file. This lock file can be build directly from the pyproject.toml (unfortunately I didn't get it to work with pypi packages while this should be supported according to the docs). Alternativly we can use our make_env.py script to create the same lock file from an environment.yml file including pypi packages. This way we could create and publish lock files with each release as part of the publishing workflow.

**Comment by savente93** [comment] 2024-01-05 11:17
You're correct on all points, my comments wasn't terribly well thought through. I guess to be a bit more clear: it's true that pixi is not ready for what we need from it at the moment.  I guess that what I meant was more along the way of "if/when pixi has support for all the things we need, it also has an integrated solution for this, which would be ideal" 

They have added an alpha pip support, and are planning to have it fully compatible with pip by the end of the year, so it's definitely something I'll be monitoring. Given that it's not ready yet, and reading through your comment I think it the approach I'd recommend depends on how urgent this issue is. We could solve this with conda-lock for now as you mentioning, but it's not clear that conda-lock and pixi lockfiles will be compatible, so it's possible that we'll have to deprecate that if we choose it now and then later want to move to pixi. 

While I agree that this is something worth fixing, I'm not sure it's something that needs fixing now and the pixi team has been moving very fast over the past few months, so personally I'm inclined to wait a little and see if we can use that directly, but I'm open to other opinions.

.

**Comment by savente93** [comment] 2024-02-27 08:54
This should be fixed by #783 since the pixi lock file it will add makes the builds reproducible

**Comment by savente93** [comment] 2024-05-28 12:48
Closing this as we are currently using pixi and commit the lock file

**Closed by savente93** 2024-05-28 12:48 UTC
Labels: Enhancement, Needs refinement, V1
