### ISSUE TITLE
Distinguish in documentation between beginner and advanced users 

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#715] opened 2024-01-10 12:17 UTC
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are unclear

### Documentation problem

Currently the documentation does not segment information according to user experience, which can create troubles for all of them. The documentation should make clear distinctions about what is for beginning users, and what is for advanced user.s

**Comment by DirkEilander** [comment] 2024-06-06 12:20
duplicate of #716

**Closed by DirkEilander** 2024-06-06 12:20 UTC
Labels: Documentation, Needs refinement, V1
