### ISSUE TITLE
update deltares data catalog based on recent DataCatalog code improvements

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#593] opened 2023-10-17 11:31 UTC
### Kind of request

None

### Enhancement Description

The predifined catalogs (deltares_data, aws_data, etc) needs to be update to reflect recent code changes. 
These include:
- variants: providers & versions
- driver_kwargs instead of kwargs
- storage_options outside of kwargs

**Comment by savente93** [comment] 2023-10-17 11:34
duplicate of #521

**Closed by savente93** 2023-10-17 11:34 UTC
Labels: Enhancement, Needs refinement
