### ISSUE TITLE
ENH: Add version numbers to data catalog yml files

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#331] opened 2023-04-21 07:28 UTC
### Feature Type

- Changing existing functionality in HydroMT

### Enhancement Description

Add hydromt version numbers to the `meta` section of the data catalog yaml file to be able to deal with potential breaking changes in the data catalog yaml format. See #327 for context.

### Feature Description

We should deal with the version in `_parse_data_dict` in data_catalog.py.
Here we should explicitly parse each key of the yml file and we can ignore keys that are unknown (e.g. from future versions or deprecated in older versions) etc.

**Comment by hboisgon** [comment] 2023-05-31 07:39
Can go together with #329

**Comment by savente93** [comment] 2023-06-27 13:48
Having had a quick brainstorming session with @DirkEilander we discussed this in conjunction with #329 but given that this has potentially bigger implications for the project because it would be a breaking change we decided to leave the issues separate. Basically if we want to add versions of the different data sets we came up with three ways of doing this. Below we've used `esa_worldcover` as an example:

```yaml
esa_worldcover:
    - crs: 4326
      data_type: RasterDataset
      driver: raster
      version: 2020
      kwargs:
        chunks:
          x: 36000
          y: 36000
      meta:
        category: landuse
        source_license: CC BY 4.0
        source_url: https://doi.org/10.5281/zenodo.5571936
        source_version: v100
      path: landuse/esa_worldcover/esa-worldcover.vrt
    - crs: 4326
      version: 2021
      data_type: RasterDataset
      driver: raster
      kwargs:
        chunks:
          x: 36000
          y: 36000
      meta:
        category: landuse
        source_license: CC BY 4.0
        source_url: https://doi.org/10.5281/zenodo.5571936
        source_version: v100
      path: landuse/esa_worldcover/esa-worldcover.vrt
```
In the example above we simply duplicate the entire entry but add an attribute for version so the use can specify which version they want. This would probably constitute the fewest changes in terms of the yaml interface but also leads to a lot of duplication and is not very easily human readable. 


```yaml
esa_worldcover:
  versions:
    - 2020:
      crs: 4326
      data_type: RasterDataset
      driver: raster
      kwargs:
        chunks:
          x: 36000
          y: 36000
      meta:
        category: landuse
        source_license: CC BY 4.0
        source_url: https://doi.org/10.5281/zenodo.5571936
        source_version: v100
      path: landuse/esa_worldcover/esa-worldcover.vrt
    - 2021:
      crs: 4326
      data_type: RasterDataset
      driver: raster
      kwargs:
        chunks:
          x: 36000
          y: 36000
      meta:
        category: landuse
        source_license: CC BY 4.0
        source_url: https://doi.org/10.5281/zenodo.5571936
        source_version: v100
      path: landuse/esa_worldcover/esa-worldcover.vrt
```
In this instance we have `esa_worldcover` and below it a mapping called `versions`, from which the user can choose. This means is conceptually a bit clearer in my opinion since the versions stay self-contained but is a bit easier to understand in terms of organisation. This would also mesh easily with the solution proposed for #329 . However it doesn't solve the duplication issue. To maintain backwards compatability, if version is not specificed we can just return the first/last instance, which would not matter in the cases where we have only one version, so this would not change current functionality (too much) 

```yaml
esa_worldcover:
  base: 
    crs: 4326
    data_type: RasterDataset
    driver: raster
    kwargs:
      chunks:
        x: 36000
        y: 36000
    meta:
      category: landuse
      source_license: CC BY 4.0
      source_url: https://doi.org/10.5281/zenodo.5571936
      source_version: v100
    path: landuse/esa_worldcover/esa-worldcover.vrt
  versions:
    - 2020:
      kwargs:
        chunks:
          x: 36000
          y: 36000
      path: landuse/esa_worldcover/esa-worldcover.vrt
    - 2021:
      kwargs:
        chunks:
          x: 36000
          y: 36000
      path: landuse/esa_worldcover/esa-worldcover.vrt
```
In the final iteration we have a base adapter for the catalog entry, and versions record changes to that. So if the user does not specify a version we could just return the base case to make sure we don't break backwards comparability, and if a version is specified, we simply make changes to the base (like the path) and return the adjusted version. The upside of this is that it makes the format leaner, since common ckeys like driver and crs only have to be recorded in the base version, and the versions only have to record things that are actually different. The downside of this is that it becomes harder to tell what exactly is being used and what all the properties used will be just by looking at the yaml. As I understand, this last one is the closest to how the alias is currently being used in some cases.

The choices here are mainly which will be best for the users. The implementations of all the above options are quite managable, so we'll have to decide which of these would be best depending on the users workflows. (Dirk, again, if I've forgotten or misremembered anything, please point it out)

**Comment by Tjalling-dejong** [comment] 2023-06-27 13:53
I implemented a version check in #334 that logs a warning when a hydromt version is specified and the version is more recent than the installed hydromt version.

@savente93 I was just typing the above comment when you posted. We are apparently talking about two different things.

**Comment by savente93** [comment] 2023-06-28 13:05
it is somewhat about different things yes, My point was more to document a conversation I had with Dirk, partially also in response to #148. I think neither of them contradict eachother

**Comment by DirkEilander** [comment] 2023-06-28 13:08
This issue is about versioning of the data_catalog file itself. @savente93 comment above is related to versioning of data sources within a data catalog file which is what we've tried to address with the `alias` key-word earlier. I've moved the comment to #148.

**Comment by savente93** [comment] 2023-07-12 09:47
@Tjalling-dejong Am i correct in thinking this was fixed in #334 ?

**Comment by savente93** [comment] 2023-07-17 09:21
@Tjalling-dejong ?

**Comment by Tjalling-dejong** [comment] 2023-07-17 11:20
Yes sorry for not replying @savente93, the issue is partially fixed in #334. In this implementation the user gets a warning whenever a version of HydroMT is specified in the datacatalog that is not the installed version of HydroMT

**Comment by savente93** [comment] 2023-07-17 13:25
ah gotcha, so all that needs to be done for this is to add the current hydromt version to the predefined catalogs right?

**Comment by savente93** [comment] 2023-08-15 08:31
closing this as it was moved to Done, so I assume it was resolved

**Closed** 2023-08-15 08:30 UTC
Labels: Enhancement, DataCatalog & DataAdapters
